[package]
name = "zebra-script"
version = "0.1.0"
authors = ["George Tankersley <george@zfnd.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.23.0"
hex = "0.4"
